### ISSUE TITLE
ENH compilation on OSX

### ISSUE THREAD

**Issue by tomMoral** [jmairal/arsenic#10]
The doc mention that it is complicated to install `cyanure` on OSX because of the lack of support for openMP.

We have been working with openMP on OSX with [`threadpoolctl`](https://github.com/joblib/threadpoolctl/blob/master/continuous_integration/install.sh) and it can be done either using `conda` compilers or using `homebrew` to add openMP support. We use the following config that enable us to compile with openMP (credit to @jeremiedbb):

```bash
       if [[ "$INSTALL_LIBOMP" == "conda-forge" ]]; then
            # Install an OpenMP-enabled clang/llvm from conda-forge
            TO_INSTALL="$TO_INSTALL conda-forge::compilers conda-forge::llvm-openmp"
            export CFLAGS="$CFLAGS -I$CONDA/envs/$VIRTUALENV/include"
            export LDFLAGS="$LDFLAGS -Wl,-rpath,$CONDA/envs/$VIRTUALENV/lib -L$CONDA/envs/$VIRTUALENV/lib"

        elif [[ "$INSTALL_LIBOMP" == "homebrew" ]]; then
            # Install a compiler with a working openmp
            HOMEBREW_NO_AUTO_UPDATE=1 brew install libomp

            # enable OpenMP support for Apple-clang
            export CC=/usr/bin/clang
            export CPPFLAGS="$CPPFLAGS -Xpreprocessor -fopenmp"
            export CFLAGS="$CFLAGS -I/usr/local/opt/libomp/include"
            export LDFLAGS="$LDFLAGS -Wl,-rpath,/usr/local/opt/libomp/lib -L/usr/local/opt/libomp/lib -lomp"
        fi
```

**Comment by jmairal** [comment]
Thanks!  A research engineer is going to join my team soon. This is one of the thing we will be looking at (+ also integrate cyanure to conda-forge).

**Comment by KranthiGV** [comment]
@jmairal Is this something you are open for me to have a look at? I can try the conda compiled openMP version out, fix any issues and update the documents as needed. Additionally, I can also work on setting up the package distribution for cyanure.

**Comment by jmairal** [comment]
Hi @KranthiGV, any help on this would be more than welcome!

**Comment by KranthiGV** [comment]
The simplest ways I could install cyanure on OSX with openmp support were:

With MKL + OpenMP
```
conda install numpy # This installs mkl, intel-openmp, etc as well
python setup_cyanure_mkl.py install OR pip install cyanure_mkl
```

With OpenBLAS + OpenMP
```
conda install openblas llvm-openmp numpy
python setup_cyanure_openblas.py install OR pip install cyanure_mkl
```

Is this something you want me to add to the documentation?
Also, @jmairal, the sphinx documentation source of the project website is not found in this repository. It still refers to the older name Arsenic (and hence contains stale version of the documentation?). Is this something you were planning to fix?

That being said, there are some tasks we could take up before we eventually make the package available on conda. A few of them are:
1. Set up a CI pipeline
2. Make the tests systematic
We could use pytest here. Currently, the dataset path (`datapath`) used in the test file is hardcoded and hence contributors cannot run the tests.
3. Make the installation across platforms systematic eventually letting us easily distribute the package via conda.
4. [ASIDE] Provide examples in the form of notebooks so that users can easily access and try out.

The above are tasks that I'm willing to discuss and take up. If that sounds okay, I can file issues and get down to the bottom of each and seek help as needed on the way.

UPDATE: The above set of tasks will lay a good foundation and makes future development easier.

**Comment by jmairal** [comment]
All of this makes a lot of sense. What I can do is to push the documentation to this repository (I have another one, which is private). I do not know how to use pytest, but it sounds like a good idea.

**Comment by KranthiGV** [comment]
That would be great, Julien. Meanwhile, I will take up some of the tasks listed above and raise PRs.

**Comment by GregoireMialon** [comment]
Hi, 

I tried to follow the installation instructions given in the sphinx doc and by @KranthiGV, which did not succed. In particular, 
`python setup_cyanure_openblas_no_openmp.py install` resulted in the following error (macOS Mojave):

`warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from cyanure_wrap_module.cpp:1:
In file included from ./utils/linalg.h:31:
In file included from ./utils/misc.h:18:
./utils/utils.h:15:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 warning and 1 error generated.
error: command 'gcc' failed with exit status 1`

Passing  '-stdlib=libc++' in `setup_cyanure_openblas_no_openmp.py` was not enough: I got another error, this time with command 'g++'. I found a work-around [here](https://github.com/pytorch/fairseq/issues/289):

> For mac os Mojave for me was using export CFLAGS='-stdlib=libc++' before calling python setup.py install

This is related although not completely relevant to the current issue but I think it may be worth clarifying this point.
