### ISSUE TITLE
Installation and "module 'cyanure' has no attribute 'MultiClassifier'"

### ISSUE THREAD

**Issue by jhjun724** [jmairal/arsenic#23]
Hello, I have a problem in using your work.

I'm trying to refer [facebookresearch/dino](https://github.com/facebookresearch/dino) and [bytedance/ibot](https://github.com/bytedance/ibot) for my research.
So, I just followed https://github.com/bytedance/ibot/blob/main/INSTALL.md.

But the first problem in installation of _cynaure_ was there is no setup_cyanure_mkl.py, maybe the version is updated.

So, I installed _cyanure_ by `pip install cyanure-mkl`, as it mentioned in https://github.com/facebookresearch/dino/issues/121#issuecomment-927158922 and http://thoth.inrialpes.fr/people/mairal/cyanure/welcome.html#installation.
It was installed successfully.

Here is the second problem. _cyanure_ is imported in python, but there is an error:
`AttributeError: module 'cyanure' has no attribute 'MultiClassifier'`

The version of cyanure-mkl is 0.22.post1.
And I also tried conda installation instead of pip, but it also has same error.

Thank you.

**Comment by homfunc** [comment]
Hello @jhjun724,
The instructions you are using are quite out of date.  I believe it is best to install the latest version of cyanure using 
`conda install cyanure`
This uses the `openblas` backend (I have not successfully built cyanure 1.0 using `mkl` yet but the `openblas` version works fine for my purposes).

The `MultiClassfier` class has gone from version 1.0 - the replacement function is demonstrated in the (updated) tutorial [Multiclass classification](https://inria-thoth.github.io/cyanure/tutorials.html#multiclass-classification).

**Comment by jmairal** [comment]
Hi @jhjun724,

note that using the old version of cyanure (via cyanure-mkl) should work if you do not want to modify the code of Dino and call the new version.  However, to do that, you need to uninstall properly cyanure before calling ```pip install cyanure-mkl'''. 

Best regards.

Julien

**Comment by jhjun724** [comment]
As I understand the comments of @homfunc  and @jmairal, to use Dino (evaluation) without any modification, I need an older version of _cyanure_, right? Can you recommend the version of cyanure to use `MultiClassifier` and installation command for pypi or conda, such as `pip install cyanure-mkl==0.X.X`?

Thank you.

**Comment by thomasryck** [comment]
Hi @jhjun724 

Indeeed if you want to use Dino (evaluation) without any installation, you have to install a version of cyanure older than 1.0.0 which can be cyanure-mkl==0.22.post1.

I suspect that you have different versions of cyanure installed could you send the result of pip list or conda list. 
Or check what I explain later. 

Since the different distribution of cyanure have been merged, there are different installation folders in your python environment if you install a pre 1.0.0 version and a post 1.0.0 version.

So if you tried to install the latest version and after cyanure-mkl, python is likely to use a latest cyanure from the cyanure folder and not from cyanure-mkl. You have to uninstall cyanure in order to be able to use cyanure-mkl
